version: "3.8"

services:
  # front:
  #   build: .
  #   container_name: load-balancer
  #   ports:
  #     - "3030:3030"
  #   command: --backends "http://web1:80,http://web2:80,http://web3:80"
  web1:
    image: strm/helloworld-http
    ports:
      - "8080:80"    

  web2:
    image: strm/helloworld-http
    ports:
      - "8081:80"    

  web3:
    image: strm/helloworld-http
    ports:
      - "8082:80"