# Reference:https://github.com/marketplace/actions/build-and-push-docker-images
name: Docker Build

on:
  workflow_run:
    workflows:
      - "Build"
    types:
      - completed
    branches:
      - "main"

jobs:
  push_to_docker_registries:
    name: Pushes Docker image to Registries
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
    - name: Set Up Qemu
      uses: docker/setup-qemu-action@v1

    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v3
      with:
        # list of Docker images to use as base name for tags
        images: |
          ${{ secrets.DOCKER_REGISTRY }}/robin-lb
          ghcr.io/${{ github.repository }}
        # generate Docker tags based on the following events/attributes
        tags: |
          type=ref,event=branch
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
          type=semver,pattern={{major}}
          type=sha        

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1

    - name: Cache Docker layers
      uses: actions/cache@v2
      id: docker_cache
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-

    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKER_REGISTRY }}
        password: ${{ secrets.DOCKER_TOKEN }}

    - name: Log In to GitHub Container Registry
      if: github.event_name != 'pull_request'
      id: ghcr_login
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Push Image to Docker Hub Registry
      uses: docker/build-push-action@v2
      id: docker_build
      with:
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ steps.meta.outputs.tags }}
        builder: ${{ steps.buildx.outputs.name }}
        cache-from: type=local,src=/tmp/.buildx-cache
        cache-to: type=local,dest=/tmp/.buildx-cache
        labels: ${{ steps.meta.outputs.labels }}

    - name: Push Image to GitHub Container Registry
      uses: docker/build-push-action@v2
      id: ghcr_docker_build
      with:
        builder: ${{ steps.buildx.outputs.name }}
        cache-from: type=local,src=/tmp/.buildx-cache
        cache-to: type=local,dest=/tmp/.buildx-cache
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}